spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/quotes
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
          format_sql: true